helm/aws-ebs-csi-driver-app/templates/networkpolicy-csi-controller.yaml

allow ebs-csi-controller to interact with k8s-api

networkpolicy fix

---

helm/aws-ebs-csi-driver-app/templates/node.yaml
helm/aws-ebs-csi-driver-app/templates/psp-csi-node.yaml

https://giphy.com/gifs/3o6wO7hfMVIEeqUTJu/html5

more power

---

helm/aws-ebs-csi-driver-app/values.yaml

- update images to the latest versions
- enable topology zone awareness and volume resizing

update images and enable features

---

helm/aws-ebs-csi-driver-app/templates/storage-class.yaml

- add sc with same parameters as we have from the in-tree plugin

add storage class

---

.circleci/config.yml

- customer can try out ebs-csi for now until we see no issues we can switch back

change catalog to playground for now

---

helm/aws-ebs-csi-driver-app/Chart.yaml
helm/aws-ebs-csi-driver-app/templates/statefulset.yaml
helm/aws-ebs-csi-driver-app/templates/storage-class.yaml
helm/aws-ebs-csi-driver-app/values.yaml

Changelog: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG-0.x.md#v080

updating to the latest version

---

helm/aws-ebs-csi-driver-app/Chart.yaml
helm/aws-ebs-csi-driver-app/templates/clusterrole-provisioner.yaml
helm/aws-ebs-csi-driver-app/templates/controller.yaml
helm/aws-ebs-csi-driver-app/templates/statefulset.yaml

this includes updating snapshot-controller to the latest version

Update ebs-csi-driver version

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/templates/clusterrole-ebs-node.yaml
helm/aws-ebs-csi-driver-app/templates/node.yaml
helm/aws-ebs-csi-driver-app/values.yaml

initial to set EBS volume limits per instance type

ebs volume limitation

---

helm/aws-ebs-csi-driver-app/Chart.yaml
helm/aws-ebs-csi-driver-app/templates/controller.yaml
helm/aws-ebs-csi-driver-app/templates/node.yaml
helm/aws-ebs-csi-driver-app/values.yaml

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG-0.x.md#v091

ebs csi v0.9.1

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/Chart.yaml
helm/aws-ebs-csi-driver-app/templates/clusterrole-ebs-node.yaml
helm/aws-ebs-csi-driver-app/templates/controller.yaml
helm/aws-ebs-csi-driver-app/templates/csidriver.yaml
helm/aws-ebs-csi-driver-app/templates/node.yaml
helm/aws-ebs-csi-driver-app/templates/statefulset.yaml
helm/aws-ebs-csi-driver-app/values.yaml

This updates ebs-csi-driver to version 1.0.0

ebs-csi-driver 1.0.0

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/templates/clusterrole-resizer.yaml
helm/aws-ebs-csi-driver-app/templates/clusterrolebinding-resizer.yaml

This should be enabled by default.

fix ebs resizing permissions

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/Chart.yaml
helm/aws-ebs-csi-driver-app/templates/controller.yaml
helm/aws-ebs-csi-driver-app/templates/service-controller.yaml
helm/aws-ebs-csi-driver-app/values.yaml

Addresses: https://github.com/giantswarm/roadmap/issues/613

enable metrics and bump csi version

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/templates/controller.yaml
helm/aws-ebs-csi-driver-app/templates/node.yaml
helm/aws-ebs-csi-driver-app/values.yaml

Change nodeSelector and ignore taints being set for nodepools.
Fixes: https://github.com/giantswarm/giantswarm/issues/20631

change nodeSelector and ignore taints being set for nodepools

---

.circleci/config.yml
CHANGELOG.md

Towards: https://github.com/giantswarm/roadmap/issues/888

Also push to control-plane app catalog.

---

helm/aws-ebs-csi-driver-app/Chart.yaml
helm/aws-ebs-csi-driver-app/aws-ebs-csi-driver-user-values
helm/aws-ebs-csi-driver-app/values.yaml

Changelog: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG-0.x.md#v160

Bump image versions

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/values.yaml

Issue - https://github.com/giantswarm/roadmap/issues/1022

Remove: imagePullSecrets from values.yaml

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/values.yaml

chart-operator already uses the port 8000.
this will change the httpEndpoint to the new port 8610.

Change overlapping port

---

helm/aws-ebs-csi-driver-app/Chart.yaml

For https://github.com/giantswarm/roadmap/issues/1248

Add icon to Chart.yml for happa

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/files/volumesnapshotclasses.yaml
helm/aws-ebs-csi-driver-app/files/volumesnapshotcontents.yaml
helm/aws-ebs-csi-driver-app/files/volumesnapshots.yaml
helm/aws-ebs-csi-driver-app/values.yaml

Updates all components to the latest versions.

Bump components

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/templates/controller.yaml
helm/aws-ebs-csi-driver-app/values.yaml

towards https://github.com/giantswarm/roadmap/issues/1687
used similar approach as used in external-dns-app

Add proxy support

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/Chart.yaml
helm/aws-ebs-csi-driver-app/values.yaml

Issue: https://github.com/giantswarm/roadmap/issues/1860

EBS CSI Driver 1.15

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/templates/crd-install/crd-job.yaml

This PR is towards https://github.com/giantswarm/roadmap/issues/2135

Add: control-plane toleration to crd-job

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/templates/crd-install/crd-cilium-np.yaml
helm/aws-ebs-csi-driver-app/values.schema.json
helm/aws-ebs-csi-driver-app/values.yaml
values.schema.json

Towards: https://github.com/giantswarm/giantswarm/issues/23014
this PR adds a cilium network policy alongside the k8s network policy to overcome cilium limitation and allow this app access to the API server.

Add cilium network policies.

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/templates/controller.yaml
helm/aws-ebs-csi-driver-app/templates/node.yaml
helm/aws-ebs-csi-driver-app/values.yaml

Towards https://github.com/giantswarm/roadmap/issues/2414

Never schedule node on control plane nodes

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/Chart.yaml
helm/aws-ebs-csi-driver-app/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/27806

Upgrade ebs-csi-driver to 1.21.0

---

CHANGELOG.md
helm/aws-ebs-csi-driver-app/templates/clusterrole-snapshot-controller.yaml
helm/aws-ebs-csi-driver-app/templates/clusterrole-snapshotter.yaml
helm/aws-ebs-csi-driver-app/templates/rolebinding-snapshot-controller-leaderelection.yaml
helm/aws-ebs-csi-driver-app/values.yaml

Update apps and fixes RBAC issues for snapshots

Rbacupdate
